_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 16
                - 23
                - 24
                - 55
            "4": 3.9.6
            "5": 0.19.1
            "8":
                - 1
                - 5
            "12": 0.19.1
            "13": darwin-arm64
